name: Publish 9-marketplace-shared

on:
  push:
    branches: [main]
    paths:
      - 'server/9-marketplace-shared/**'
  pull_request:
    branches: [main]
    paths:
      - 'server/9-marketplace-shared/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    defaults:
      run:
        working-directory: ./server/9-marketplace-shared

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://npm.pkg.github.com/

      - run: npm install

      - run: npm run build

      - run: |
          echo @eldadmamo:registry=https://npm.pkg.github.com/ > .npmrc
          echo '//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}' >> .npmrc

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}